name: budgetbuddy
description: A budget tracking application.
publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.5
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  firebase_app_check: ^0.3.0+9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  firebase_messaging: ^15.1.3
  fl_chart: ^0.63.0
  flutter_local_notifications: ^19.4.2
  flutter_timezone: ^5.0.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  timezone: ^0.10.1
  share_plus: ^10.0.2
  package_info_plus: ^8.0.2
  pdf: ^3.11.0
  image: ^4.2.0
  file_picker: ^8.0.7
  archive: ^3.4.10
  permission_handler: ^12.0.1



dependency_overrides:


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/g-logo.png
    - assets/app_logo.png
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/budgetbuddy_icon.png"
  min_sdk_android: 21
